In [2]:
import pandas as pd

In [3]:
country_codes = pd.read_csv('./data/country_codes.csv')
rankings = pd.read_csv('./data/fifa_rankings.csv')
matches = pd.read_csv('./data/matches.csv')

In [4]:
matches

,match_id,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
0,1,1872-11-30,Scotland,England,0.0,0.0,Friendly,Glasgow,Scotland,False
1,2,1873-03-08,England,Scotland,4.0,2.0,Friendly,London,England,False
2,3,1874-03-07,Scotland,England,2.0,1.0,Friendly,Glasgow,Scotland,False
3,4,1875-03-06,England,Scotland,2.0,2.0,Friendly,London,England,False
4,5,1876-03-04,Scotland,England,3.0,0.0,Friendly,Glasgow,Scotland,False
...,...,...,...,...,...,...,...,...,...,...
44159,44160,2022-11-21,Senegal,Netherlands,0.0,2.0,FIFA World Cup,Doha,Qatar,True
44160,44161,2022-11-21,England,Iran,6.0,2.0,FIFA World Cup,Al Rayyan,Qatar,True
44161,44162,2022-11-21,United States,Wales,1.0,1.0,FIFA World Cup,Al Rayyan,Qatar,True
44162,44163,2022-11-22,Argentina,Saudi Arabia,1.0,2.0,FIFA World Cup,Lusail,Qatar,True
44163,44164,2022-11-22,Denmark,Tunisia,0.0,0.0,FIFA World Cup,Al Rayyan,Qatar,True

In [5]:
rankings['rank_date'].iloc[0]

'1992-12-31'

In [6]:
matches_trimmed = matches.copy()

In [7]:
# Trim matches
matches_trimmed.drop(matches_trimmed[matches_trimmed['date'] <= rankings['rank_date'].iloc[0]].index, inplace = True)
matches_trimmed

,match_id,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
17697,17698,1993-01-01,Ghana,Mali,1.0,1.0,Friendly,Libreville,Gabon,True
17698,17699,1993-01-02,Gabon,Burkina Faso,1.0,1.0,Friendly,Libreville,Gabon,False
17699,17700,1993-01-02,Kuwait,Lebanon,2.0,0.0,Friendly,Kuwait City,Kuwait,False
17700,17701,1993-01-03,Burkina Faso,Mali,1.0,0.0,Friendly,Libreville,Gabon,True
17701,17702,1993-01-03,Gabon,Ghana,2.0,3.0,Friendly,Libreville,Gabon,False
...,...,...,...,...,...,...,...,...,...,...
44159,44160,2022-11-21,Senegal,Netherlands,0.0,2.0,FIFA World Cup,Doha,Qatar,True
44160,44161,2022-11-21,England,Iran,6.0,2.0,FIFA World Cup,Al Rayyan,Qatar,True
44161,44162,2022-11-21,United States,Wales,1.0,1.0,FIFA World Cup,Al Rayyan,Qatar,True
44162,44163,2022-11-22,Argentina,Saudi Arabia,1.0,2.0,FIFA World Cup,Lusail,Qatar,True
44163,44164,2022-11-22,Denmark,Tunisia,0.0,0.0,FIFA World Cup,Al Rayyan,Qatar,True

In [8]:
# Countries in Rankings but NOT in Matches


# first see which countries are in rankings but not in matches
countries_in_rankings_not_in_matches = list(set(rankings['country_full'].unique()) - set(matches_trimmed['home_team'].unique()))

# Create series with all countries in matches and the number of matches
countries_list_matches = rankings['country_full'].value_counts()

# Then filter the  list of matches using the countries that are in matches but not in federation
print((countries_list_matches.loc[countries_in_rankings_not_in_matches]).sort_values(ascending=False))

# This way we see how we should reformat the countries from confederations

IR Iran                  322
Korea Republic           322
Korea DPR                322
CÃ´te d'Ivoire            322
Congo DR                 322
St. Lucia                322
Brunei Darussalam        322
USA                      322
Kyrgyz Republic          307
St. Kitts and Nevis      305
Chinese Taipei           291
US Virgin Islands        243
Yugoslavia               102
Netherlands Antilles      44
Serbia and Montenegro     43
Czechoslovakia             6
Name: country_full, dtype: int64

In [9]:
print(list(set(matches_trimmed['home_team'].unique()) - set(rankings['country_full'].unique())))

['Iran', 'Padania', 'Parishes of Jersey', 'FelvidÃ©k', 'Kyrgyzstan', 'Yoruba Nation', 'Ellan Vannin', 'Palau', 'Isle of Man', 'Orkney', 'Provence', 'County of Nice', 'Basque Country', 'Barawa', 'Silesia', 'French Guiana', 'Western Sahara', 'Raetia', 'Tuvalu', 'Saint Helena', 'Kiribati', 'FrÃ¸ya', 'Darfur', 'Western Armenia', 'Micronesia', 'North Korea', 'United States Virgin Islands', 'Falkland Islands', 'Aymara', 'Occitania', 'Northern Mariana Islands', 'Saare County', 'South Korea', 'Saint Kitts and Nevis', 'Monaco', 'Saint Pierre and Miquelon', 'Matabeleland', 'Iraqi Kurdistan', 'Sark', 'Arameans Suryoye', 'Saint Lucia', 'Brunei', 'Somaliland', 'Sint Maarten', 'Hitra', 'Gotland', 'Catalonia', 'Saint Martin', 'Alderney', 'Vatican City', 'GÄƒgÄƒuzia', 'Yorkshire', 'Corsica', 'Jersey', 'Abkhazia', 'Guadeloupe', 'United Koreans in Japan', 'SÃ¡pmi', 'Zanzibar', 'Artsakh', 'Isle of Wight', 'Bonaire', 'Guernsey', 'SzÃ©kely Land', 'DR Congo', 'Andalusia', 'Romani people', 'Ynys MÃ´n', 'Kernow', 'Rhodes', 'KÃ¡rpÃ¡talja', 'Mapuche', 'Brittany', 'Greenland', 'Panjab', 'Canary Islands', 'Western Isles', 'Menorca', 'Gozo', 'Martinique', 'Republic of St. Pauli', 'Galicia', 'Ã…land Islands', 'Madrid', 'Chagos Islands', 'United States', 'Kabylia', 'Chameria', 'Ivory Coast', 'South Ossetia', 'Mayotte', 'Taiwan', 'Shetland', 'Cascadia', 'Biafra', 'Tamil Eelam', 'Tibet', 'Northern Cyprus', 'RÃ©union']

In [10]:
print(list(set(matches_trimmed['home_team'].unique()) - set(country_codes['team'].unique())))

['Padania', 'Parishes of Jersey', 'FelvidÃ©k', 'Yoruba Nation', 'Ellan Vannin', 'Palau', 'Isle of Man', 'Orkney', 'Provence', 'County of Nice', 'Basque Country', 'Barawa', 'Silesia', 'French Guiana', 'Western Sahara', 'Raetia', 'Tuvalu', 'Saint Helena', 'Kiribati', 'FrÃ¸ya', 'Darfur', 'Western Armenia', 'Micronesia', 'United States Virgin Islands', 'Falkland Islands', 'Aymara', 'Occitania', 'Northern Mariana Islands', 'Saare County', 'Monaco', 'Saint Pierre and Miquelon', 'Matabeleland', 'Iraqi Kurdistan', 'Sark', 'Arameans Suryoye', 'Somaliland', 'Sint Maarten', 'Hitra', 'Gotland', 'Catalonia', 'Saint Martin', 'Alderney', 'Vatican City', 'GÄƒgÄƒuzia', 'Yorkshire', 'Corsica', 'Jersey', 'Abkhazia', 'Guadeloupe', 'United Koreans in Japan', 'SÃ¡pmi', 'Zanzibar', 'Artsakh', 'Isle of Wight', 'Bonaire', 'Guernsey', 'SzÃ©kely Land', 'China PR', 'Andalusia', 'Romani people', 'Ynys MÃ´n', 'Kernow', 'Rhodes', 'KÃ¡rpÃ¡talja', 'Mapuche', 'Brittany', 'Greenland', 'Panjab', 'Canary Islands', 'Western Isles', 'Menorca', 'Gozo', 'Martinique', 'Republic of St. Pauli', 'Galicia', 'Ã…land Islands', 'Madrid', 'Chagos Islands', 'Kabylia', 'Chameria', 'South Ossetia', 'Mayotte', 'Taiwan', 'Shetland', 'Cascadia', 'Biafra', 'Tamil Eelam', 'Tibet', 'Northern Cyprus', 'RÃ©union']

In [11]:
len(list(set(matches_trimmed['home_team'].unique()) - set(country_codes['team'].unique())))

90

In [12]:
# Countries IN Matches but NOT IN Rankings


# first see which countries are in matches but not in rankings
countries_in_matches_not_in_rankings = list(set(matches_trimmed['home_team'].unique()) - set(rankings['country_full'].unique()))

# Create series with all countries in matches and the number of matches
countries_list = matches_trimmed['home_team'].value_counts()

# Then filter the list of matches using the countries that are in matches but not in rankings (first 25 with most matches)
print((countries_list.loc[countries_in_matches_not_in_rankings]).sort_values(ascending=False).head(25))

United States                   339
South Korea                     269
Iran                            202
Ivory Coast                     162
DR Congo                        127
Saint Kitts and Nevis            93
Martinique                       91
North Korea                      80
Guadeloupe                       71
Saint Lucia                      63
Kyrgyzstan                       63
French Guiana                    48
Jersey                           46
Guernsey                         37
Padania                          28
Zanzibar                         28
United States Virgin Islands     26
Greenland                        26
Ynys MÃ´n                         25
Basque Country                   24
Isle of Wight                    24
Catalonia                        23
Taiwan                           22
Isle of Man                      22
Brunei                           21
Name: home_team, dtype: int64

In [13]:
rankings.loc[rankings['country_full']=='IR Iran']

,rank,country_full,country_abrv,total_points,previous_points,rank_change,confederation,rank_date
118,61,IR Iran,IRN,24.00,0.00,0,AFC,1992-12-31
296,54,IR Iran,IRN,32.00,24.00,-7,AFC,1993-08-08
433,58,IR Iran,IRN,31.00,32.00,4,AFC,1993-09-23
567,59,IR Iran,IRN,30.00,31.00,1,AFC,1993-10-22
733,58,IR Iran,IRN,31.00,30.00,-1,AFC,1993-11-19
...,...,...,...,...,...,...,...,...
62915,21,IR Iran,IRN,1572.89,1557.58,0,AFC,2022-02-10
63222,21,IR Iran,IRN,1564.49,1572.89,0,AFC,2022-03-31
63339,23,IR Iran,IRN,1558.64,1564.49,2,AFC,2022-06-23
63647,22,IR Iran,IRN,1558.64,1558.64,-1,AFC,2022-08-25
63856,20,IR Iran,IRN,1564.61,1558.64,-2,AFC,2022-10-06

In [14]:
matches_trimmed.loc[matches_trimmed['home_team']=='CuraÃ§ao']

,match_id,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
19211,19212,1995-05-14,CuraÃ§ao,Aruba,3.0,2.0,CFU Caribbean Cup qualification,Willemstad,Netherlands Antilles,True
19225,19226,1995-05-25,CuraÃ§ao,Puerto Rico,2.0,2.0,CFU Caribbean Cup qualification,Santo Domingo,Dominican Republic,True
19768,19769,1996-03-23,CuraÃ§ao,Grenada,0.0,1.0,CFU Caribbean Cup qualification,Willemstad,Netherlands Antilles,True
19857,19858,1996-05-11,CuraÃ§ao,Dominican Republic,0.0,0.0,FIFA World Cup qualification,Willemstad,Netherlands Antilles,True
21470,21471,1998-03-07,CuraÃ§ao,French Guiana,2.0,1.0,CFU Caribbean Cup qualification,Oranjestad,Aruba,True
...,...,...,...,...,...,...,...,...,...,...
42282,42283,2021-03-25,CuraÃ§ao,Saint Vincent and the Grenadines,5.0,0.0,FIFA World Cup qualification,Willemstad,CuraÃ§ao,False
42570,42571,2021-06-08,CuraÃ§ao,Guatemala,0.0,0.0,FIFA World Cup qualification,Willemstad,CuraÃ§ao,False
42644,42645,2021-06-15,CuraÃ§ao,Panama,0.0,0.0,FIFA World Cup qualification,Willemstad,CuraÃ§ao,False
43043,43044,2021-10-09,CuraÃ§ao,New Zealand,1.0,2.0,Friendly,Riffa,Bahrain,True
43667,43668,2022-06-03,CuraÃ§ao,Honduras,0.0,1.0,CONCACAF Nations League,Willemstad,CuraÃ§ao,False

In [15]:
matches.loc[matches['home_team']=='Serbia']

,match_id,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
19130,19131,1995-03-31,Serbia,Uruguay,1.0,0.0,Friendly,Belgrade,Yugoslavia,False
19238,19239,1995-05-31,Serbia,Russia,1.0,2.0,Friendly,Belgrade,Yugoslavia,False
19790,19791,1996-03-27,Serbia,Romania,1.0,0.0,Friendly,Belgrade,Yugoslavia,False
19830,19831,1996-04-24,Serbia,Faroe Islands,3.0,1.0,FIFA World Cup qualification,Belgrade,Yugoslavia,True
19948,19949,1996-06-02,Serbia,Malta,6.0,0.0,FIFA World Cup qualification,Belgrade,Yugoslavia,True
...,...,...,...,...,...,...,...,...,...,...
43094,43095,2021-10-12,Serbia,Azerbaijan,3.0,1.0,FIFA World Cup qualification,Belgrade,Serbia,False
43138,43139,2021-11-11,Serbia,Qatar,4.0,0.0,Friendly,Belgrade,Serbia,False
43651,43652,2022-06-02,Serbia,Norway,0.0,1.0,UEFA Nations League,Belgrade,Serbia,False
43715,43716,2022-06-05,Serbia,Slovenia,4.0,1.0,UEFA Nations League,Belgrade,Serbia,False
43990,43991,2022-09-24,Serbia,Sweden,4.0,1.0,UEFA Nations League,Belgrade,Serbia,False

In [16]:
matches_trimmed.loc[matches['home_team']=='Montenegro']

,match_id,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
29373,29374,2007-03-24,Montenegro,Hungary,2.0,1.0,Friendly,Podgorica,Montenegro,False
29788,29789,2007-08-22,Montenegro,Slovenia,1.0,1.0,Friendly,Podgorica,Montenegro,False
29915,29916,2007-09-12,Montenegro,Sweden,1.0,2.0,Friendly,Podgorica,Montenegro,False
30387,30388,2008-03-26,Montenegro,Norway,3.0,1.0,Friendly,Podgorica,Montenegro,False
30493,30494,2008-05-27,Montenegro,Kazakhstan,3.0,0.0,Friendly,Podgorica,Montenegro,False
...,...,...,...,...,...,...,...,...,...,...
43542,43543,2022-03-28,Montenegro,Greece,1.0,0.0,Friendly,Podgorica,Montenegro,False
43698,43699,2022-06-04,Montenegro,Romania,2.0,0.0,UEFA Nations League,Podgorica,Montenegro,False
43845,43846,2022-06-11,Montenegro,Bosnia and Herzegovina,1.0,1.0,UEFA Nations League,Podgorica,Montenegro,False
44012,44013,2022-09-26,Montenegro,Finland,0.0,2.0,UEFA Nations League,Podgorica,Montenegro,False
44110,44111,2022-11-17,Montenegro,Slovakia,2.0,2.0,Friendly,Podgorica,Montenegro,False

In [17]:
matches_trimmed.loc[matches['home_team']=='Serbia and Montenegro'].head(20)

Empty DataFrame
Columns: [match_id, date, home_team, away_team, home_score, away_score, tournament, city, country, neutral]
Index: []

In [18]:
matches_trimmed['home_team'].value_counts().tail(30)

Tibet                        4
Darfur                       4
Republic of St. Pauli        4
Canary Islands               4
Kiribati                     3
GÄƒgÄƒuzia                     3
Western Sahara               3
Gozo                         3
Arameans Suryoye             3
Matabeleland                 2
Micronesia                   2
Somaliland                   2
FelvidÃ©k                     2
Parishes of Jersey           2
Yoruba Nation                2
Biafra                       2
Vatican City                 2
Mapuche                      2
Raetia                       2
Cascadia                     2
Saint Helena                 1
Chameria                     1
Palau                        1
Kabylia                      1
Saint Pierre and Miquelon    1
Romani people                1
Sark                         1
Silesia                      1
Madrid                       1
Aymara                       1
Name: home_team, dtype: int64

In [22]:
matches_trimmed.loc[matches_trimmed['country']=='Czechoslovakia']

Empty DataFrame
Columns: [match_id, date, home_team, away_team, home_score, away_score, tournament, city, country, neutral]
Index: []

In [37]:
matches.loc[matches['country']=='Yugoslavia']

,match_id,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
642,643,1922-06-08,Yugoslavia,Romania,1.0,2.0,Friendly,Belgrade,Yugoslavia,False
649,650,1922-06-28,Yugoslavia,Czechoslovakia,4.0,3.0,Friendly,Zagreb,Yugoslavia,False
669,670,1922-10-01,Yugoslavia,Poland,1.0,3.0,Friendly,Zagreb,Yugoslavia,False
780,781,1924-02-10,Yugoslavia,Austria,1.0,4.0,Friendly,Zagreb,Yugoslavia,False
840,841,1924-09-28,Yugoslavia,Czechoslovakia,0.0,2.0,Friendly,Zagreb,Yugoslavia,False
...,...,...,...,...,...,...,...,...,...,...
24566,24567,2001-08-15,Serbia,Faroe Islands,2.0,0.0,FIFA World Cup qualification,Belgrade,Yugoslavia,True
24638,24639,2001-09-05,Serbia,Slovenia,1.0,1.0,FIFA World Cup qualification,Belgrade,Yugoslavia,True
24688,24689,2001-10-06,Serbia,Luxembourg,6.0,2.0,FIFA World Cup qualification,Belgrade,Yugoslavia,True
25055,25056,2002-04-17,Serbia,Lithuania,4.0,1.0,Friendly,Smederevo,Yugoslavia,False
25427,25428,2002-10-16,Serbia,Finland,2.0,0.0,UEFA Euro qualification,Belgrade,Yugoslavia,False

In [46]:
matches_trimmed.loc[(matches_trimmed['date'] > '1990-01-01') & (matches_trimmed['country']=='Yugoslavia')]

,match_id,date,home_team,away_team,home_score,away_score,tournament,city,country,neutral
19130,19131,1995-03-31,Serbia,Uruguay,1.0,0.0,Friendly,Belgrade,Yugoslavia,False
19238,19239,1995-05-31,Serbia,Russia,1.0,2.0,Friendly,Belgrade,Yugoslavia,False
19790,19791,1996-03-27,Serbia,Romania,1.0,0.0,Friendly,Belgrade,Yugoslavia,False
19830,19831,1996-04-24,Serbia,Faroe Islands,3.0,1.0,FIFA World Cup qualification,Belgrade,Yugoslavia,True
19948,19949,1996-06-02,Serbia,Malta,6.0,0.0,FIFA World Cup qualification,Belgrade,Yugoslavia,True
20360,20361,1996-11-10,Serbia,Czech Republic,1.0,0.0,FIFA World Cup qualification,Belgrade,Yugoslavia,True
20609,20610,1997-03-12,Serbia,Russia,0.0,0.0,Friendly,Belgrade,Yugoslavia,False
20781,20782,1997-04-30,Serbia,Spain,1.0,1.0,FIFA World Cup qualification,Belgrade,Yugoslavia,True
20877,20878,1997-06-08,Serbia,Slovakia,2.0,0.0,FIFA World Cup qualification,Belgrade,Yugoslavia,True
21269,21270,1997-11-15,Serbia,Hungary,5.0,0.0,FIFA World Cup qualification,Belgrade,Yugoslavia,True
21544,21545,1998-04-22,Serbia,South Korea,3.0,1.0,Friendly,Belgrade,Yugoslavia,False
21597,21598,1998-05-29,Serbia,Nigeria,3.0,0.0,Friendly,Belgrade,Yugoslavia,False
21814,21815,1998-09-02,Serbia,Switzerland,1.0,1.0,Friendly,NiÅ¡,Yugoslavia,False
22014,22015,1998-11-18,Serbia,Republic of Ireland,1.0,0.0,UEFA Euro qualification,Belgrade,Yugoslavia,False
22551,22552,1999-08-18,Serbia,Croatia,0.0,0.0,UEFA Euro qualification,Belgrade,Yugoslavia,False
22587,22588,1999-09-05,Serbia,North Macedonia,3.0,1.0,UEFA Euro qualification,Belgrade,Yugoslavia,False
23020,23021,2000-03-28,Serbia,China PR,1.0,0.0,Friendly,Belgrade,Yugoslavia,False
24042,24043,2001-03-24,Serbia,Switzerland,1.0,1.0,FIFA World Cup qualification,Belgrade,Yugoslavia,True
24191,24192,2001-04-25,Serbia,Russia,0.0,1.0,FIFA World Cup qualification,Belgrade,Yugoslavia,True
24566,24567,2001-08-15,Serbia,Faroe Islands,2.0,0.0,FIFA World Cup qualification,Belgrade,Yugoslavia,True
24638,24639,2001-09-05,Serbia,Slovenia,1.0,1.0,FIFA World Cup qualification,Belgrade,Yugoslavia,True
24688,24689,2001-10-06,Serbia,Luxembourg,6.0,2.0,FIFA World Cup qualification,Belgrade,Yugoslavia,True
25055,25056,2002-04-17,Serbia,Lithuania,4.0,1.0,Friendly,Smederevo,Yugoslavia,False
25427,25428,2002-10-16,Serbia,Finland,2.0,0.0,UEFA Euro qualification,Belgrade,Yugoslavia,False